--select for ID
CREATE PROCEDURE SELECT_CATEGORIES
	@CATEGORY_ID INT
AS
	SELECT CategoryID, CategoryName, Description, Picture 
	FROM Categories
	WHERE CategoryID = @CATEGORY_ID;
GO

exec SELECT_CATEGORIES 7
--selectAll
CREATE PROCEDURE SELECT_ALL_CATEGORIES
AS
	SELECT CategoryID, CategoryName, Description, Picture 
	FROM Categories;
GO
--insert
CREATE PROCEDURE INSERT_CATEGORIES
	@CATEGORY_NAME NVARCHAR(15),
	@DESCRIPTION NTEXT = NULL,
	@PICTURE IMAGE = NULL
AS
	INSERT INTO Categories(CategoryName, Description, Picture)
	VALUES(@CATEGORY_NAME, @DESCRIPTION, @PICTURE);
GO
--update
CREATE PROCEDURE UPDATE_CATEGORIES
	@CATEGORY_ID INT,
	@CATEGORY_NAME NVARCHAR(15),
	@DESCRIPTION NTEXT = NULL,
	@PICTURE IMAGE = NULL
AS
	UPDATE Categories 
	SET CategoryName = @CATEGORY_NAME, Description = @DESCRIPTION, Picture = @PICTURE  
	WHERE CategoryID = @CATEGORY_ID;
GO
--delete
CREATE PROCEDURE DELETE_CATEGORIES
	@CATEGORY_ID INT
AS
	DELETE FROM Categories 
	WHERE CategoryID = @CATEGORY_ID;
GO
--searchName
CREATE PROCEDURE SEARCH_NAME_CATEGORIES
	@CATEGORY_NAME NVARCHAR(15)
AS
	SELECT CategoryID, CategoryName, Description, Picture 
	FROM Categories
	WHERE CategoryName LIKE '%'+@CATEGORY_NAME+'%';
GO
--searchDescription
CREATE PROCEDURE SEARCH_DESCRIPTION__CATEGORIES
	@DESCRIPTION NVARCHAR(MAX)	
AS
	SELECT CategoryID, CategoryName, Description, Picture 
	FROM Categories
	WHERE Description LIKE '%'+@DESCRIPTION+'%';
GO



